name: Jekyll Format
on: [ push, pull_request ]
jobs:
  run:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        ocaml-compiler: [ '4', '5' ]
    steps:
    - uses: actions/checkout@v2
    - uses: ocaml/setup-ocaml@v3
      with:
        ocaml-compiler: ${{ matrix.ocaml-compiler }}
    - run: opam pin add jekyll-format.dev -n .
    - name: Dependencies
      run: opam install -t . --deps-only
    - name: Build
      run: opam exec -- dune build
    - name: Test
      run: opam exec -- dune runtest
